---
variables:
  E_lep: true
  E_avail: true
  E_nu: true
  Lepton_Pt: true
  Lepton_Pl: true
  Theta_lep: true
  Proton_p: true
  Proton_Pt: true
  Theta_p: true
  Proton_T: true

  DeltaPt: true
  DeltaPtX: true
  DeltaPtY: true
  DeltaPl: true
  P_n: true
  AlphaPt: true
  PhiPt: true

precuts:
  HasTracks:
    enabled: true

  NoVertexMismatch:
    enabled: true

  ZRange:
    enabled: true
    minZ: 5980 #in mm
    maxZ: 8422 #in mm

  Apothem:
    enabled: true
    apothem: 850 #in mm
    
  StartPointVertexMultiplicity:
    enabled: true
    
  Afterpulsing:
    enabled: true
    minFirstFireFraction: 0.25 #more than 25% of electron candidate hits are first fire hits (first time firing in gate)
    
  NoDeadtime:
    enabled: true #no more than 1 dead channel upstream of electron track

  HasNoBackExitingTracks:
    enabled: true

  SideExitingMuon:
    enabled: true
    
  DSCalVisE:
    enabled: true
    maxDSCalRatio: 0.2 #ratio of energy in DS hcal / DS ecal
    
  ODCalVisE:
    enabled: true
    maxSideCalRatio: 0.05 #ratio of energy in OD hcal / side ecal

  VertexTrackMultiplicity:
    enabled: true
    minVertexTrackMultiplicity: 0 
    maxVertexTrackMultiplicity: 2 #max number of tracks leaving the neutrino vertex

  TransverseGapScore:
    enabled: true
    minTransverseGapScore: 15 #unitless spread score

  NonMIPClusterFraction:
    enabled: true
    minNonMIPClusFrac: 0.7 # fraction of energy from trackable clusters / electron energy

  EMLikeTrackScore:
    enabled: true
    minEMTrackScore: 0.7 #kNN track score

  MichelCut: #this and meanfront dEdX are sideband cuts, so they are disabled here and enabled there
    enabled: false

  MeanFrontdEdX:
    enabled: false
    maxMeanFrontDEDX: 2.4 # in MeV/cm

  ElectronEnergy:
    enabled: true
    minElectronEnergy: 2500 #in MeV

  ModifiedEavailable:
    enabled: true
    maxModifiedEAvail: 600 #in MeV #was 1000

  ProtonInEvent:
    enabled: true 

  NIsoBlobs:
    enabled: true
    maxNIsoBlobs: 2

  IsoBlobEnergy:
    enabled: false
    maxIsoBlobEnergy: 250 #in MeV
    
  UpstreamIsoBlob:
    enabled: false
    furthestUpstreamIsoBlobStartZ: -50 #in mm, meaning no blobs more than x mm upstream of vertex
    
  ESC:
    enabled: true
    maxESCChi2: 20 #proton ESC track chi^2, was at 10

sideband_cuts:
  MichelCut:
    enabled: true

  MeanFrontdEdX:
    enabled: true
    maxMeanFrontDEDX: 2.4 #in MeV/cm
  
sidebands: #sideband histograms to fill
  MeanFrontDEDXSB: true
  MichelSB: true
  NIsoClusSB: false
  NPiSB: false

#systematics: false
systematics: true
